version: '3'
services:
  website:
      image: nginx
      ports: 
        - "8081:80"
      restart: always
  website2:
      image: nginx
      ports: 
        - "8082:80"
      restart: always
      networks:
        platzi_composer:
          ipv4_address: 192.168.92.5

networks:
  platzi_composer:
      ipam:
        driver: default
        config: 
          - subnet: 192.168.92.0/24
          - ip_range: 192.168.92.7
